services:
  backend:
    build:
      context: ./backend
      args:
        - MONGO_URI=mongodb://mongo:27017/todo
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - PORT=5000
      - JWT_SECRET=miclavesecretaultrasegura123
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo:6.0
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
 
